grid_search:
  class : GridSearchCV
  module : sklearn.model_selection
  params:
    cv : 5
    verbose : 2 

model_selection:
  module_0:
    class: SVC
    module: sklearn.svm
    params: 
      kernel: rbf
      gamma : scale
    search_param_grid:
      kernel:
        - rbf
        - poly
        - sigmoid
      degree:
        - 2
        - 4
        - 3
      gamma:
        - scale
        - auto
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      criterion: gini
      max_depth: 3
      min_samples_split: 2
      min_samples_leaf: 2
    search_param_grid:
      criterion:
        - gini
        - entropy
      max_depth:
        - 3
        - 4
      min_samples_split:
        - 3
        - 4 

  module_2:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 70
      algorithm: SAMME
    search_param_grid:
      algorithm:
        - SAMME.R
      
      
