grid_search:
  class : GridSearchCV
  module : sklearn.model_selection
  params:
    cv : 5
    verbose : 2 

model_selection:
  module_0:
    class: SVC
    module: sklearn.svm
    params:
      kernel: rbf
      gamma: scale
    search_param_grid:
      kernel:
        - rbf
        - poly
        - sigmoid
      degree:
        - 2
        - 4
        - 3
      gamma:
        - scale
        - auto
        
  module_1:
    class: SGDClassifier
    module: sklearn.linear_model
    params:
      loss : hinge
      penalty: l2
    search_param_grid:
      loss:
        - hinge
      penalty:
        - l1
        - l2
        - elasticnet
      
      

  
      
      
