columns:
  Intercolumnar_distance: float
  upper_margin : float
  lower_margin : float
  exploitation : float
  row_number : float
  modular_ratio : float
  inter_linear_spacing : float
  weight : float
  peak_number : float
  modular_ratio/inter_linear_spacing : float
  Class : category

target_column : Class 

numerical_columns:
  - Intercolumnar_distance
  - upper_margin
  - lower_margin
  - exploitation
  - row_number
  - modular_ratio
  - inter_linear_spacing
  - weight
  - peak_number
  - modular_ratio/inter_linear_spacing

